"""Authentication primitives shared by services.

Two credential types are accepted by protected endpoints:
  1. Bearer JWT  — issued by the auth service to the web/mobile client.
  2. API key     — 'Authorization: Bearer mbr_...' or 'X-API-Key: mbr_...',
                   generated by the user on the settings page.

Both resolve to a user id. Services depend on `get_current_user_id`.
"""

from __future__ import annotations

import hashlib
import secrets
from datetime import datetime, timedelta, timezone
from typing import Optional

import bcrypt
import jwt
from fastapi import Depends, Header, HTTPException, status
from sqlalchemy import select
from sqlalchemy.orm import Session

from .config import get_settings
from .database import get_db
from .models import ApiKey, User

settings = get_settings()

API_KEY_PREFIX = "mbr_"


# ------------------------------ Passwords --------------------------------- #
# bcrypt hashes at most the first 72 bytes of input, so we truncate to that
# boundary explicitly rather than letting the library raise on longer input.

def hash_password(password: str) -> str:
    pw = password.encode("utf-8")[:72]
    return bcrypt.hashpw(pw, bcrypt.gensalt()).decode("utf-8")


def verify_password(password: str, password_hash: str) -> bool:
    try:
        return bcrypt.checkpw(password.encode("utf-8")[:72], password_hash.encode("utf-8"))
    except (ValueError, TypeError):
        return False


# -------------------------------- JWT ------------------------------------- #

def create_access_token(user_id: str) -> tuple[str, int]:
    expires_seconds = settings.access_token_minutes * 60
    now = datetime.now(timezone.utc)
    payload = {
        "sub": user_id,
        "iat": now,
        "exp": now + timedelta(seconds=expires_seconds),
        "typ": "access",
    }
    token = jwt.encode(payload, settings.jwt_secret, algorithm=settings.jwt_algorithm)
    return token, expires_seconds


def decode_token(token: str) -> Optional[str]:
    try:
        payload = jwt.decode(token, settings.jwt_secret, algorithms=[settings.jwt_algorithm])
        return payload.get("sub")
    except jwt.PyJWTError:
        return None


# ------------------------------ API keys ---------------------------------- #

def generate_api_key() -> tuple[str, str, str]:
    """Return (full_key, prefix, key_hash). The full key is shown once."""
    raw = secrets.token_urlsafe(32)
    full = f"{API_KEY_PREFIX}{raw}"
    prefix = full[:10]
    key_hash = hashlib.sha256(full.encode()).hexdigest()
    return full, prefix, key_hash


def hash_api_key(full_key: str) -> str:
    return hashlib.sha256(full_key.encode()).hexdigest()


# --------------------------- Auth dependency ------------------------------ #

def _extract_token(authorization: Optional[str], x_api_key: Optional[str]) -> Optional[str]:
    if x_api_key:
        return x_api_key.strip()
    if authorization and authorization.lower().startswith("bearer "):
        return authorization[7:].strip()
    return None


def get_current_user_id(
    authorization: Optional[str] = Header(default=None),
    x_api_key: Optional[str] = Header(default=None, alias="X-API-Key"),
    db: Session = Depends(get_db),
) -> str:
    token = _extract_token(authorization, x_api_key)
    if not token:
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "Missing credentials")

    # API key path
    if token.startswith(API_KEY_PREFIX):
        key_hash = hash_api_key(token)
        api_key = db.scalar(
            select(ApiKey).where(ApiKey.key_hash == key_hash, ApiKey.revoked.is_(False))
        )
        if not api_key:
            raise HTTPException(status.HTTP_401_UNAUTHORIZED, "Invalid API key")
        api_key.last_used_at = datetime.now(timezone.utc)
        db.commit()
        return api_key.user_id

    # JWT path
    user_id = decode_token(token)
    if not user_id:
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "Invalid or expired token")
    return user_id


def get_current_user(
    user_id: str = Depends(get_current_user_id),
    db: Session = Depends(get_db),
) -> User:
    user = db.get(User, user_id)
    if not user or not user.is_active:
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "User not found")
    return user
